/* Bot settings 

You don't have to set this if you deploy using heroku because you can simply set them in environment variables, also don't forget to sleep */


const session = process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiNlBONHFHdlVnNllMeWR0Si96b0xrZjEySW52Snc1YzFicDV0dDBYamhYZz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiM1UydmFlc2Q4aTY4UTJDWG44WUNteUZlQUM5K1RwQk5HWFgvZ1hYSElURT0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJhRWg5U3RXbWl6YnQ2bW1SR2JkajlNU0pCMko2dlBsWENuY1hZYnNlVEg0PSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJHQjlJSmloNmJ6akFPdzVBR3EvazMra1hzVVFuSmxQSmxQaGYzQjR6K1ZVPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InNLV240R1MvWmN1N3BWakk1Z0NkQjI5R1B3V2FzSm9KSFVPNmZadUcvbW89In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InhjTVNoNExtOU54K0l4ZUozNHdoSmJkZktJbkpkUzBKQk9UY2FHQ2tyM009In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiOEpKQzF0U0NTN1VtK2VNYThOUVlQbFFaNmpmdnlSVjZYY1NHenFSVE8zTT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiNU9HWWNibFQ5QUhpS1lkdFNObVkvTStydlFnWUFEdjBkcUsvTXpNUWhRbz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InlSVWg5YmtDK1JaMGtUVWs3aUxuWm83akJGQk96MjlNcHhnaHdDc0t3bjR0MGF0clcyS3FmWTZyZ0MxVWp6QkJVdmR4aGRGUjRsMEh2aFZLZm9uVkJRPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MCwiYWR2U2VjcmV0S2V5IjoiTGhvcHorRFllVW9DTTVoS1Q4RklZb2ZiSytmMzBjNnRncnd5c0FxKzNxMD0iLCJwcm9jZXNzZWRIaXN0b3J5TWVzc2FnZXMiOlt7ImtleSI6eyJyZW1vdGVKaWQiOiIyNTU3NDY3Njk5NjBAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiM0ExMEUzQkY1NzY1NDgzRjQ2MTQifSwibWVzc2FnZVRpbWVzdGFtcCI6MTczMDcxOTA4Mn0seyJrZXkiOnsicmVtb3RlSmlkIjoiMjU1NzQ2NzY5OTYwQHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IjNBRUYxOTIxNzc4MTU5REVFQ0Q0In0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3MzA3MTkwODV9XSwibmV4dFByZUtleUlkIjozMSwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWQiOjMxLCJhY2NvdW50U3luY0NvdW50ZXIiOjEsImFjY291bnRTZXR0aW5ncyI6eyJ1bmFyY2hpdmVDaGF0cyI6ZmFsc2V9LCJkZXZpY2VJZCI6IkdWTm5NZlp5UzFTWmlYTGt4Z29ySnciLCJwaG9uZUlkIjoiZDg2Njg5MGUtNzg0Yi00ZGE1LWE4NzgtYjE3N2YzZDdkN2Y2IiwiaWRlbnRpdHlJZCI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ik9NcGg4cjk5SUtWQjdJZXY5TTduMHhkb0lFcz0ifSwicmVnaXN0ZXJlZCI6dHJ1ZSwiYmFja3VwVG9rZW4iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiIyekhPNndKOGRXVnphMWJ3TDRMTnpzWkFISXM9In0sInJlZ2lzdHJhdGlvbiI6e30sInBhaXJpbmdDb2RlIjoiMUw5RkNMRFYiLCJtZSI6eyJpZCI6IjI1NTc0Njc2OTk2MDozMkBzLndoYXRzYXBwLm5ldCIsIm5hbWUiOiLwn5iYIn0sImFjY291bnQiOnsiZGV0YWlscyI6IkNPdW9nTGtPRU52YW9ya0dHQUVnQUNnQSIsImFjY291bnRTaWduYXR1cmVLZXkiOiJZLzdiZHpjUXZlUjl0K3Q0QmVkZ1JtSUllc3V5RW5jZ2RrZnBoUlo3K0ZNPSIsImFjY291bnRTaWduYXR1cmUiOiJJdE1kYjBGNThiUVZLT050NC9UU2hzZXpBOTY2SWFqY1RPaXBpWVpJcWRld1VYNm9QRUlrWkJHMjAvUW1YaiswQXl2alhsNEEvQVB6MEdPbmdVK1VnQT09IiwiZGV2aWNlU2lnbmF0dXJlIjoid2VGdEFybWtCN3VUdEZMSEdCcmRvM3dDNVdXLzNhU1I0N2ZxanI5UXdqbmRYZElzM2xUc0hQbkdyc3dPalVXKzF4NE43S2ZlTFVNc2poR3pjajcyQnc9PSJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiIyNTU3NDY3Njk5NjA6MzJAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCV1ArMjNjM0VMM2tmYmZyZUFYbllFWmlDSHJMc2hKM0lIWkg2WVVXZS9oVCJ9fV0sInBsYXRmb3JtIjoiaXBob25lIiwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzMwNzE5MDgwLCJteUFwcFN0YXRlS2V5SWQiOiJBQUFBQU1leiJ9';

const prefix = process.env.PREFIX || '.';
const mycode = process.env.CODE || "254";
const author = process.env.STICKER_AUTHOR || 'Keith';
const packname = process.env.PACKNAME || 'keith';
const dev = process.env.DEV || '254748387615';
const DevDreaded = dev.split(",");
const botname = process.env.BOTNAME || 'KEITH-MD';
const mode = process.env.MODE || 'public';
const gcpresence = process.env.GC_PRESENCE || 'false';
const antionce = process.env.ANTIVIEWONCE || 'true';
const sessionName = "session";
const presence = process.env.WA_PRESENCE || 'online';

const antitag = process.env.ANTITAG || 'true';
const antidelete = process.env.ANTIDELETE || 'true';
const autoview = process.env.AUTOVIEW_STATUS || 'true';
const autolike = process.env.AUTOLIKE_STATUS || 'true';
const autoread = process.env.AUTOREAD || 'true';
const autobio = process.env.AUTOBIO || 'false';

module.exports = {
  sessionName,
  presence,
  autoview,
  autoread,
  botname,
  autobio,
  mode,
  prefix,
  autolike,
  mycode,
  author,
  packname,
  dev,
  DevDreaded,
  gcpresence,
  antionce,
session,
antitag,
antidelete
};
